<a href="https://colab.research.google.com/github/lokeshchowdary9220/AML-Lab/blob/main/overfitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
from sklearn.datasets import fetch_california_housing






data =fetch_california_housing()
df = pd.DataFrame(data.data)
df.head()

        0     1         2         3       4         5      6       7
0  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25

In [48]:
df["target"] = data.target

df.head()

        0     1         2         3       4         5      6       7  target
0  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23   4.526
1  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22   3.585
2  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24   3.521
3  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25   3.413
4  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25   3.422

In [10]:
print("Number of Rows and Columns ",df.shape)

Number of Rows and Columns  (1727, 7)

In [25]:
x = df.drop("target", axis=1)
y = df["target"]

In [26]:
# Split the dataset into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42)

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

decision_model = DecisionTreeClassifier(random_state=42)

decision_model.fit(x_train, y_train)

decision_pred = decision_model.predict(x_test)

In [28]:
# Predict using the Decision Tree model
decision_pred = decision_model.predict(x_test)

print(decision_pred)

[6 9 3 7 2 1 5 3 5 7 2 7 4 0 4 2 3 7 8 8 4 3 9 7 5 6 3 5 6 3 4 9 1 4 4 6 9
 4 7 6 6 9 1 3 6 1 3 0 6 5 5 1 3 5 6 0 3 0 0 8 5 4 8 2 4 5 7 0 7 5 9 9 5 4
 7 0 4 5 5 9 9 0 2 3 8 0 6 4 4 1 1 2 5 3 9 2 9 4 4 7 4 3 4 3 8 3 5 9 4 2 7
 7 4 7 1 9 2 7 3 3 2 6 9 4 0 7 5 7 5 8 7 5 7 3 0 6 6 4 2 8 0 9 4 6 9 9 6 9
 0 3 5 6 6 0 6 4 3 9 3 3 7 2 9 0 4 5 8 6 5 4 9 8 4 2 1 5 7 7 2 2 3 9 8 0 3
 3 2 5 6 9 9 4 4 2 4 2 3 6 4 8 5 9 5 7 1 9 4 8 1 5 4 4 9 6 1 8 6 0 4 5 2 7
 8 6 4 5 6 9 3 2 3 6 7 1 9 1 4 7 6 9 1 5 5 1 4 4 8 8 7 9 7 0 2 8 2 3 2 9 1
 3 6 0 9 7 7 0 1 0 4 5 1 5 3 6 0 4 1 0 4 3 6 5 9 7 7 5 9 9 9 8 5 3 2 2 0 5
 8 3 4 0 8 4 6 4 3 4 5 0 5 2 1 3 1 4 7 1 7 0 1 5 6 1 3 8 7 0 6 4 8 8 5 1 8
 4 5 9 7 9 8 5 0 5 2 0 7 9 8 9 5 2 7 4 9 9 7 4 3 8 9 5]

In [29]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

# Evaluate the Decision Tree model
print('Accuracy Score:', accuracy_score(y_test, decision_pred))
print('Recall Score:', recall_score(y_test, decision_pred, average='weighted'))
print('Precision Score:', precision_score(y_test, decision_pred, average='weighted'))
print('F1 Score:', f1_score(y_test, decision_pred, average='weighted'))

# Confusion Matrix
print('Confusion Matrix:\n', confusion_matrix(y_test, decision_pred))

Accuracy Score: 0.8416666666666667
Recall Score: 0.8416666666666667
Precision Score: 0.8456094561708596
F1 Score: 0.8417863834021484
Confusion Matrix:
 [[29  0  0  0  2  1  0  0  0  1]
 [ 0 22  1  0  1  0  0  1  2  1]
 [ 0  0 24  3  1  1  1  1  2  0]
 [ 0  0  1 29  0  1  0  1  1  1]
 [ 0  0  1  0 42  0  0  2  1  0]
 [ 0  0  1  0  1 40  0  0  1  4]
 [ 1  0  0  0  1  1 32  0  0  0]
 [ 0  0  0  2  1  0  0 31  0  0]
 [ 0  3  0  1  0  1  0  0 21  4]
 [ 0  1  0  3  1  0  0  2  0 33]]

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#To check overfitting
train_pred = decision_model.predict(x_train)
test_pred = decision_model.predict(x_test)

print("Training Accuracy:",
      accuracy_score(y_train, train_pred))

print("Testing Accuracy:",
      accuracy_score(y_test, test_pred))

print("Tree Depth:", decision_model.get_depth())

Training Accuracy: 1.0
Testing Accuracy: 0.8416666666666667
Tree Depth: 15

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Train the full Decision Tree
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

# 2. Get possible ccp_alpha values
path = tree.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas

# 3. Try every alpha and find the best one
best_alpha = 0
best_test_accuracy = 0
best_tree = None

for alpha in ccp_alphas:

    pruned_tree = DecisionTreeClassifier(
        random_state=42,
        ccp_alpha=alpha
    )

    pruned_tree.fit(X_train, y_train)

    train_pred = pruned_tree.predict(X_train)
    test_pred = pruned_tree.predict(X_test)

    train_accuracy = accuracy_score(y_train, train_pred)
    test_accuracy = accuracy_score(y_test, test_pred)

    if test_accuracy > best_test_accuracy:
        best_test_accuracy = test_accuracy
        best_alpha = alpha
        best_tree = pruned_tree


# 4. Display the best post-pruned tree
train_pred = best_tree.predict(X_train)
test_pred = best_tree.predict(X_test)

print("POST-PRUNED DECISION TREE")
print("-------------------------")
print(f"Best CCP Alpha: {best_alpha:.5f}")
print(f"Training Accuracy: {accuracy_score(y_train, train_pred) * 100:.2f}%")
print(f"Testing Accuracy: {accuracy_score(y_test, test_pred) * 100:.2f}%")
print(f"Tree Depth: {best_tree.get_depth()}")
print(f"Number of Leaves: {best_tree.get_n_leaves()}")

POST-PRUNED DECISION TREE
-------------------------
Best CCP Alpha: 0.00177
Training Accuracy: 94.43%
Testing Accuracy: 86.11%
Tree Depth: 13
Number of Leaves: 70

In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

depths = [2, 3, 5, 7, 10, 15,20,25]

for depth in depths:

    tree = DecisionTreeClassifier(
        max_depth=depth,
        random_state=42
    )

    tree.fit(x_train, y_train)

    train_pred = tree.predict(x_train)
    test_pred = tree.predict(x_test)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)

    print(
        f"Max Depth: {depth} | "
        f"Train: {train_acc * 100:.2f}% | "
        f"Test: {test_acc * 100:.2f}% | "
        f"Actual Depth: {tree.get_depth()}"
    )

Max Depth: 2 | Train: 32.50% | Test: 29.72% | Actual Depth: 2
Max Depth: 3 | Train: 47.32% | Test: 47.22% | Actual Depth: 3
Max Depth: 5 | Train: 67.43% | Test: 66.39% | Actual Depth: 5
Max Depth: 7 | Train: 89.14% | Test: 82.22% | Actual Depth: 7
Max Depth: 10 | Train: 96.87% | Test: 85.00% | Actual Depth: 10
Max Depth: 15 | Train: 100.00% | Test: 84.17% | Actual Depth: 15
Max Depth: 20 | Train: 100.00% | Test: 84.17% | Actual Depth: 15
Max Depth: 25 | Train: 100.00% | Test: 84.17% | Actual Depth: 15